# Generated by Django 4.2.9 on 2024-05-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainphoto_remove_photo_description_photo_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='Описание фотографии', max_length=100),
        ),
    ]
