# Generated by Django 4.2.9 on 2024-05-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photo_caption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPhoto',
        ),
    ]
