# Generated by Django 4.2.9 on 2024-05-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_alter_photo_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('photo', models.ImageField(upload_to='review_photos')),
            ],
        ),
    ]
