# Generated by Django 4.2.9 on 2024-05-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
