# Generated by Django 4.2.9 on 2024-05-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_action_delete_slideritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='author2',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='photo',
            new_name='photo2',
        ),
    ]
