# Generated by Django 4.2.9 on 2024-05-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_service_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
