# Generated by Django 4.2.9 on 2024-05-17 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appointment_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='application',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service'),
        ),
    ]
