# Generated by Django 4.2.9 on 2024-05-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='author2',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='photo2',
            new_name='photo',
        ),
    ]
